# version: '3.7'

# services:
#   n8n:
#     image: n8nio/n8n:latest
#     ports:
#       - "5678:5678"
#     environment:
#     - DB_TYPE=postgresdb
#     - DB_POSTGRESDB_HOST=aws-0-ap-south-1.pooler.supabase.com
#     - DB_POSTGRESDB_PORT=5432
#     - DB_POSTGRESDB_DATABASE=postgres
#     - DB_POSTGRESDB_USER=postgres.dgicjssnfashtwapexij
#     - DB_POSTGRESDB_PASSWORD=OMz5zHLtV8NIdmGx
#     - N8N_BASIC_AUTH_ACTIVE=true
#     - N8N_BASIC_AUTH_USER=tech@indq.in
#     - N8N_BASIC_AUTH_PASSWORD=Adminpass1
#     - N8N_HOST=0.0.0.0
#     - N8N_PORT=5678
#     - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
#     # - N8N_PROTOCOL=https
#     # - WEBHOOK_URL=https://indqchatbot.zmake.in
#     # - N8N_EDITOR_BASE_URL=https://indqchatbot.zmake.in
#     volumes:
#       - ./data:/home/node/.n8n

      

#     networks:
#       - chatbot-network

  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   command: tunnel --config /etc/cloudflared/config.yml run
  #   volumes:
  #     - ./cloudflared:/etc/cloudflared
  #   depends_on:
  #     - n8n
  #   networks:
  #     - chatbot-network
  #   restart: unless-stopped

# volumes:
#   n8n_data:

# networks:
#   chatbot-network:
#     driver: bridge


#docker-compose exec n8n n8n import:workflow --input=/home/node/.n8n/INDQ_ChatBot.json    

# services:
#   n8n:
#     image: n8nio/n8n:latest
#     ports:
#       - "5678:5678"
#     environment:
#       - N8N_BASIC_AUTH_ACTIVE=true
#       - N8N_BASIC_AUTH_USER=tech@indq.in
#       - N8N_BASIC_AUTH_PASSWORD=Adminpass1
#     volumes:
#       - ./data:/home/node/.n8n

# networks:
#   n8n-net:
#     driver: bridge

version: '3.7'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Basic Configuration
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      
      # Authentication
      - N8N_BASIC_AUTH_ACTIVE=true
      
      # Webhook & Editor URL
      - N8N_WEBHOOK_URL=https://indqchatbot.zmake.in
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      
      # Database Configuration
      - DB_TYPE=postgres
      - DB_POSTGRESDB_HOST=aws-0-ap-south-1.pooler.supabase.com
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=postgres
      

    volumes:
      - ./data:/home/node/.n8n
      - ./n8n.env:/home/node/.n8n/.env:ro
    networks:
      - chatbot-network
    depends_on:
      - cloudflared

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      - chatbot-network
    restart: unless-stopped

networks:
  chatbot-network:
    driver: bridge

volumes:
  n8n_data: