version: '3.7'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:

      - N8N_HOST=indqchatbot.zmake.in 
      - N8N_PORT=5678
      - N8N_PROTOCOL=https       
      - WEBHOOK_URL=https://indqchatbot.zmake.in
      - WEBHOOK_TUNNEL_URL=https://indqchatbot.zmake.in
      # Authentication
      - N8N_BASIC_AUTH_ACTIVE=true
      
      # Webhook & Editor URL
      - N8N_WEBHOOK_URL=https://indqchatbot.zmake.in
      - N8N_EDITOR_BASE_URL=https://indqchatbot.zmake.in
      
      # Database Configuration
      - DB_TYPE=postgres
      - DB_POSTGRESDB_HOST=aws-0-ap-south-1.pooler.supabase.com
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=postgres
      

    volumes:
      - ./data:/home/node/.n8n
      - ./n8n.env:/home/node/.n8n/.env:ro
    networks:
      - chatbot-network
    depends_on:
      - cloudflared

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      - chatbot-network
    restart: unless-stopped

networks:
  chatbot-network:
    driver: bridge

volumes:
  n8n_data: